### ISSUE TITLE
Typos in Github project description

### ISSUE THREAD

**Issue by Havvy** [hohl/irc-socket-factory#1]
Currently the description states:

`Toolkit build on irc-socket by Havy to manage multiple persistent IRC sockets.`

The two typos are:
1. `build` should be `built`.
2. `Havy` should be `Havvy` or omitted.

Fixed versions:

`Toolkit built on irc-socket by Havvy to manage multiple persistent IRC sockets.`

`Toolkit built on irc-socket to manage multiple persistent IRC sockets.`

**Comment by hohl** [comment]
Sorry for that, will be fixed of course.
